cisco/node-jose

package.json
"browserify" is listed in both "dependencies" and "devDependencies", but only needed when developing/building.
=> Build: browserify is only a devDependency

README.md, lib/util/base64url.js, package.json, test/util/base64url-test.js
This replaces the internal implementation for base64url encoding/decoding with one from https://github.com/brianloveswords/base64url.  The breaking change here is `.decode(string)` -- previously it returned a Buffer, or a string if an explicit encoding was provided.  Now it only ever returns a buffer.
=> Breaking: use external implementation of base64url (Close #10)

lib/jwe/decrypt.js, lib/jws/verify.js
Previously when a key was provided to decrypt it would use the keys keystore to find a key.
If the given key was not the first key found in the keystore, then the decryption would fail.
suggested to fix #14
=> When an assumed key is provided, use it

README.md, lib/util/base64url.js, package.json
Switches from brianloveswords/base64url to RGBboy/urlsafe-base64 (patched).
PR submitted for an enhancement to .encode strings (and arrays, arraybuffers, typed arrays).
=> Fix: base64url does not work on IE (fix #16)

lib/jwk/eckey.js, lib/jwk/keystore.js, test/jwk/keystore-test.js
The extra fields allow non-JSON-string imported keys (for instance PEM) to have additional JWK fields
added on to the fields captured from the import.  In particular, fields like a corresponding x5t can
be added to a private RSA key so that tokens generated in the presence of the public x509 cert can
use that as a key identifier instead of or in addition to kid.
=> Added x5t generation when importing a cert and extra fields

lib/deps/forge.js
The changes to setImmediate to address errors in node v0.10 re-introduced problems with IE10.  Latest seems to work with IE10 and node v0.10.
=> Fix: address errors with setImmediate in IE

README.md
README.md claims that one has to call `verify` to decrypt. The correct call is `decrypt`.
=> fix wrong decryption sample code in README.md

lib/algorithms/helpers.js
There's one remaining occurence of `require("es6-promise").polyfill();` which is not wrapped in check statement. Now while the choice of polyfill is questionable (i.e. why not just include Bluebird) the absolute minimum requirement is that the default ES6 Promise is not replaced after requiring node-jose.
```
$ node -v
v4.2.2
$ node
> Promise
[Function: Promise]
> require('node-jose')
...
> Promise
{ [Function: lib$es6$promise$promise$$Promise]
all: [Function: lib$es6$promise$promise$all$$all],
race: [Function: lib$es6$promise$promise$race$$race],
resolve: [Function: lib$es6$promise$promise$resolve$$resolve],
reject: [Function: lib$es6$promise$promise$reject$$reject],
_setScheduler: [Function: lib$es6$promise$asap$$setScheduler],
_setAsap: [Function: lib$es6$promise$asap$$setAsap],
_asap: …
```
=> fix: polyfill always loaded with node-jose

test/jwk/keystore-test.js, test/jwk/rsakey-test.js
Original PEM tests were included as part of another testcase.  This separates it out to be more explicit in the reporting.
=> Build: Separate RSA PEM tests into their own testcase.

lib/jwk/eckey.js, test/jwk/eckey-test.js, test/jwk/keystore-test.js
Builds upon RSA-only implementation to also export Elliptic Curve keys.
=> Update: export EC keys as PEM

lib/jwk/basekey.js, test/jwk/basekey-test.js
Prevents the private key being included if a JWK is nested inside another object and toJSON() is implicitly called.
=> Fix: only honor isPrivate if it is actually a Boolean

lib/algorithms/helpers.js
Can't see why this is needed. Also it makes webpack generate a warning on build
```
./~/node-jose/lib/algorithms/helpers.js
Critical dependencies:
53:13-29 the request of a dependency is an expression
@ ./~/node-jose/lib/algorithms/helpers.js 53:13-29
```
=> Eliminates warning when using with webpack

lib/jwk/rsakey.js
Generating RSA keys blocks the event loop, this is painfully obvious with 2048 bit size. Using this simple script you can check the before and after for this PR.
```js
'use strict';
var jose = require('.');
var ks = jose.JWK.createKeyStore();
let i = 0;
let count = () => {
console.log(i++);
setImmediate(count);
}
count();
console.log('RSA pre');
ks.generate('RSA', 2048).then(() => console.log('RSA callback')).then(() => process.exit(0))
console.log('RSA after');
```
*before*
```
0
RSA pre
(blocks loop)
RSA after
RSA callback
exits
```
*after*
```
0
RSA pre
RSA after
1
2
3
... (continues executing)
RSA callback
exits
```
=> use callback signature for forge.pki.rsa.generateKeyPair in node environments

.travis.yml, gulpfile.js, package.json
This includes SauceLabs for pushes, and xvfb+Firefox for PRs.
=> Build: include browser tests in travis-ci

lib/util/base64url.js, package.json
This PR implements the two extra features of linuxwolf/urlsafe-base64 on top of a standard published package.
In combination with #103 this will resolve #96
=> remove urlsafe enc/dec tar dependency

lib/jwe/encrypt.js, lib/jws/sign.js, test/jwe/embed-test.js, test/jws/embed-test.js
=> Update: prevent embedding 'oct' keys in JWS objects

lib/jwk/keystore.js
When adding a key to a KeyStore that is already in JSON format the input jwk is modified when creating the Key.
```javascript
var jose = require('node-jose')
// !!!! this jwk variable should not change
var jwk = {
kty: 'RSA',
kid: 'v9nlkBvs0_bA9zJcyfUeyqDMXT_VpSVvUvktvOmoqCI',
e: 'AQAB',
n: 'tyaZ2IG7DkzfhhSLDFcoGdH-JXctfTZ-C1ICc_o9BABZqY1ZDk1dhztElvKvb_FrcJDh_8uvY9E7TO7dqN6m7bUaBwICjsEXUNrGpYHkzTyPR8UpFLtzVFKmVs17nLSK4J1grgLmarBs_VAroLDc8M2djmxqkA6UuifZ3DoiWuyNho_Xw31o-qk2HY4jRSvmlvMFlLMM9zjYeznn0mFGNqghBkuk6e4ie0sQwMKZMKsvqeew19VCDOPSzsHH-W_mK67rOASk8jm6_CeYLR66yja2qMjuGh6s9h_MuhKEW8nqmmZajafKsRo2mI5l1jVRtLTdqJjBJkI3Iwys122cgw' 
}
jose.JWK.asKey(jwk).then(function () {
console.log(jwk)
})
```
prints
```
{ 
kty: 'RSA',
kid: 'v9nlkBvs0_bA9zJcyfUeyqDMXT_VpSVvUvktvOmoqCI',
e: 'AQAB',
n: …
```
=> prevent JWK.KeyStore#add from modifying jwk input

package.json
If using the scp-like Git URL syntax [1], a colon (':') must be used
after the server part. Better not use that syntax anyway but the
more common HTTP protocol, which also is GitHub's default.
[1] https://git-scm.com/book/en/v2/Git-on-the-Server-The-Protocols#_the_ssh_protocol
=> package: Fix wrong repository URL syntax

AUTHORS, lib/algorithms/aes-gcm.js, lib/jwk/octkey.js, package.json, test/jwe/jwe-test.js, test/jwk/octkey-test.js
=> remove A*GCMKW support

README.md, lib/jwk/keystore.js, test/jwk/keystore-test.js
Provides a convenience "top-level" method to generate a key without an explicit keystore.
=> Create a Key without first creating a KeyStore

lib/util/base64url.js, package-lock.json, package.json, test/jwe/allowedalg-test.js
Hi @linuxwolf,
the base64url package has a found [vulnerability](https://hackerone.com/reports/321687) currently reported by snyk and other tools. The report history shows attempts to contact the maintainer for a fix with no success since march 2017.
b64u is a drop-in replacement with the vulnerability fixed. It'd be great if you could fast-forward a patch release with this fix.
Also, there was a forgotten .only in the test suite.
=> drop in replace base64url due to a vulnerability

lib/util/base64url.js, package.json
I can see you're getting ready for 🤞1.0.0 or simply another minor. This is to pull the original / more "visible" base64 url package back in. See also https://github.com/cisco/node-jose/pull/179#issuecomment-389331647
=> 3.0.0 base64url

lib/algorithms/aes-gcm.js, lib/algorithms/pbes2.js, lib/jwe/encrypt.js, lib/jwk/octkey.js, test/algorithms/aes-gcm-test.js, test/algorithms/pbes2-test.js, test/jwe/implicit-header-test.js, test/jwe/jwe-test.js, test/jwk/octkey-test.js
Closes #133 
When wrapping keys in JWE, the algorithm can generate a missing value and it'll be applied to the JWE header(s).
For `A*GCMKW`:
* generate `"iv"` of 12 random bytes
For `PBES2-*`:
* generate `"p2s"` of 16 random bytes
* apply `"p2c"` of 8192
=> Update: generate and apply header values when key wrapping

test/jwe/crit-test.js, test/jws/crit-test.js
If the line `assert.ok(false, "unexpected success");` would throw, then it would get caught in the catch function. By moving the catch function to the second argument of `then` as opposed to a chained `catch` method call, it ensures that only errors from `decrypt(jwe)` will get caught.
> I just noticed this while skimming through the tests to get a better understanding of the module. Apologies if I'm wrong about the bug.
=> fix test assertion that would get ignored

.travis.yml, lib/algorithms/aes-kw.js, lib/algorithms/ec-util.js, lib/algorithms/ecdsa.js, lib/algorithms/rsa-util.js, lib/algorithms/rsaes.js, lib/algorithms/rsassa.js, lib/deps/forge.js, lib/jwk/eckey.js, lib/jws/verify.js, test/algorithms/ecdsa-test.js
- fixes correct jws verify input validation `typeof` check
- make use of native node crypto for AES-KW Key-Wrapping
- make use of native node crypto for RS signing
- make use of native node crypto for RSA-OAEP and RSA1_5 encryption
- make use of native node crypto for RSA-PSS
- make use of native node crypto for RSA1_5 decryption
- makes use of native node crypto for ECDSA
- removes setImmediate/nextTick IE workaround
I kindly ask for a review, especially for aa5a48d which as noted is inspired by another published implementation
with this in place the only use of `node-forge` in node lts/carbon is for converting keys between formats and `RSA-OAEP-256`
closes #203
fixes #210
closes #202
Note: can we remove non lts versions of node from travis? `RSASSA-PSS` support was added in `^6.12.0 || …
=> make more use of node crypto + more

package-lock.json, package.json, test/algorithms/ecdsa-test.js
Edge fails with "invalid calling object" because of some incorrect detection logic within `node-forge`.
Safari fails because it does not support NIST curve `P-521`.  While this PR addresses both, the most impactful is Edge.
=> bug: fix failures on Edge

README.md
There seems to be an inconsistency in the REAMDE between `allowAlgs` and `algorithms` when restricting which verification and decryption algorithms can be used via the options object.  Looking at the code, it appears that `algorithms` is correct.
=> README algorithm restriction inconsistent - s/allowAlgs/algorithms/g

README.md
This PR drops statements in the documentation about simple booleans for 'crit' header verification. This feature is not implemented, so it should be removed  from the documentation.
=> remove documentation for not implemented crit header handling

lib/util/databuffer.js
Fix: #266 
Do not replace forge.util.ByteBuffer with util.databuffer.DataBuffer
=> Do not replace forge.util.ByteBuffer (#266)

lib/index.js, package.json
Hi maintainers,
I'm trying to integrate this library into my react and react-native projects.
I believe, the following small changes will help:
- add `buffer` dependency, and polyfill global `Buffer`
- add `process` dependency, and minimally polyfill global `process`
- add `browserify-zlib` dependency for browser type environment
- add `react-zlib-js` dependency for react-native type environment
=> Add better react and react-native compatibility

lib/algorithms/aes-cbc-hmac-sha2.js, lib/algorithms/aes-kw.js, lib/algorithms/hmac.js, lib/algorithms/sha.js
When I was working with this library, I noticed that I was getting invalid results.
When the library is not able to access `crypto` and `WebCrypto API` modules, it defaults to using some fallback functions, which rely mostly on `node-forge`. I have found that some of the logic are throwing errors.
We can simulate this condition by the following:
1. Patch the `helpers.setupFallback()` method to always use fallback algorithms
file: `lib/algorithms/helpers.js`
lines: [92 - 94](https://github.com/cisco/node-jose/blob/master/lib/algorithms/helpers.js#L94)
```javascript
// other codes
exports.setupFallback = function(nodejs, webcrypto, fallback) {
var impl;
nodejs = false; // add this
webcrypto = false; // add this
if (nodejs && exports.nodeCrypto) {
// other codes
```
2. Run the test suites …
=> fix algorithms fallback functions

lib/jwe/decrypt.js, lib/jwe/encrypt.js, package.json
Hi team,
I'm a fellow Cisco employee working on the Webex JS SDK.
We're working on getting some of our projects working with the upcoming webpack v5, which loses node builtins.
This libraries' use of zlib is raising an error and while it would be easier to just alias it in the webpack config, we'd like to move off webpack to something else.
I've been deep-diving into our SDK to see what else needs to be "polyfilled"/"isomorphed" so we dont need to use node only version of packages
We also need to update `node-scr` and `node-kms` to use the latest version of `node-jose`
=> Replace browserify-zlib with webpack v5 compatible pako

gulpfile.js, lib/algorithms/ec-util.js, lib/algorithms/ecdh.js, lib/algorithms/rsa-util.js, lib/deps/ciphermodes/gcm/helpers.js, lib/jwe/encrypt.js, lib/jwk/basekey.js, lib/jwk/helpers.js, lib/jwk/keystore.js, lib/jws/sign.js, lib/jws/verify.js, lib/util/merge.js, test/algorithms/ecdh-test.js, test/jwe/invalidecdh-test.js, test/jwe/jwe-test.js, test/jwe/roundtrip-test.js, test/jwk/eckey-test.js, test/jwk/octkey-test.js, test/jwk/rsakey-test.js, test/jws/jws-test.js, test/parse/compact-test.js, test/parse/index-test.js, test/parse/json-test.js
node-jose heavily depends on lodash. When using node-jose in a webpack base project, all lodash modules will be included in the bundle files, resulting in a big bundled js.
[babel-plugin-lodash](https://github.com/lodash/babel-plugin-lodash) provides a way to decrease the bundled file size. But it doesn't work with node-jose because node-jose doesn't use ES2015 import syntax.
This PR manually cherry-pick the needed lodash modules and make the bundle smaller.
Here's the comparison. The stat size is decreased from 527.84kb to 167.13kb.
=> Cherry-pick lodash modules to make webpack bundle files smaller

.gitignore, .travis.yml, package-lock.json, package.json
Update dependencies to latest, clearing out most `npm audit` reports.
**NOTE** this also sets the minimum version for Node from v6 (**UNMAINTAINED**) to v10.
=> [fix] Update Dependencies

lib/jwe/encrypt.js, package.json
After the recent release of `2.0.0`, and merge of this PR #287 , I noticed that some fallback functions were failing unit tests.
When the library is not able to access `crypto` and `WebCrypto API` modules, it defaults to using some fallback functions, which rely mostly on `node-forge` and now `pako`. I have found that some of the logic are throwing errors.
We can simulate this condition by the following:
1. Patch the `helpers.setupFallback()` method to always use fallback algorithms
file: `lib/algorithms/helpers.js`
lines: [92 - 94](https://github.com/cisco/node-jose/blob/master/lib/algorithms/helpers.js#L94)
```javascript
// other codes
exports.setupFallback = function(nodejs, webcrypto, fallback) {
var impl;
nodejs = false; // add this
webcrypto = false; // add this
if (nodejs && …
```
=> minor fixes for react-native and fallback methods

README.md
99.8% sure these examples were erroneous.
=> Minor README example fixes

lib/jwe/decrypt.js, test/jwe/default-alg.js
Addresses #312.
An explicit options argument overwrites the internal defaults when provided to `new JWEDecrypter(ks, globalOpts)` or `JWE.createDecrypt(ks, globalOpts)`.
This causes an error when decrypting tokens after an explicit algorithm option was provided to a previous decrypt attempt.
The added test case demonstrates that decrypting an `a256gcm` token works fine at first, but the following `a256kw` does not, even though the assumed default is `algorithms: "*"` which should let the token through the decryption.
=> fix accidental merge of DEFAULT_OPTIONS in JWEDecrypter
