cisco/node-jose

README.md, lib/jws/verify.js, test/jws/jws-test.js
PR for #5 - Adds signing key verified to the verify() result.
=> Issue 5: Enhance to return key from verify

gulpfile.js
Adds the most recent versions of IE (10, 11) and Safari (7, 8, 9).
=> Build: expand the saucelabs platforms

AUTHORS, lib/jwk/basekey.js, lib/jwk/rsakey.js, package.json, test/jwk/rsakey-test.js
=> Add toPEM and toDER for RSA keys

lib/jwk/eckey.js, lib/jwk/keystore.js, lib/jwk/rsakey.js, test/jwk/keystore-test.js
This enhancement provides better interoperability with what OpenSSL key generation outputs.
=> Support importing EC and RSA "raw" PEM keys (Close #33)

README.md, lib/jwk/basekey.js, lib/jwk/eckey.js, lib/jwk/helpers.js, lib/jwk/octkey.js, lib/jwk/rsakey.js, test/jwk/basekey-test.js, test/jwk/eckey-test.js, test/jwk/keystore-test.js, test/jwk/octkey-test.js, test/jwk/rsakey-test.js
Addresses issue #21, and an alternative to PR #22.
=> Update: implement JWK thumbprint support [RFC 7638]

lib/algorithms/concat.js, lib/algorithms/hmac.js, lib/jwe/encrypt.js, lib/jwk/keystore.js, lib/jws/sign.js, lib/jws/verify.js
Fixed
- four cases of string-rejections
- two cases of Promise returning methods to reject instead of throwing
=> fix throws and rejects to be error objects and consistent

lib/algorithms/constants.js
=> Fix: typo in lib/algorithms/constants.js

package.json
=> Build: reconcile git-prefixed dependencies

README.md, lib/jws/verify.js, test/jws/embed-test.js, test/jws/jws-test.js
=> Update: find keys embedded in JWS header(s)

lib/jwe/decrypt.js, lib/jws/verify.js
=> Fix: node v6+ emits UnhandledPromiseRejectionWarning

lib/jwe/decrypt.js
=> Fix: improper call to base64url.decode

lib/algorithms/rsa-util.js, lib/algorithms/rsaes.js, lib/algorithms/rsassa.js
This improves the performance of cracking certain jwks by 15x.
=> Use native RSA/OpenSSL crypto whenever possible

test/jwe/embed-test.js
Fixes a mistakenly limited test config
=> run all tests

.npmignore, package-lock.json
Fixes a mistakenly limited test config
=> Build: bundle package-lock.json for devel

lib/jwk/keystore.js, test/jwk/keystore-test.js
=> coerce "kid" during lookup

README.md
* Add notes about key usage for sign/verify and encrypt/decrypt
* Notes about handling `crit` members
=> Doc: Updates to README

lib/index.js, lib/jws/verify.js
canYouSee alias to createVerify
=> Jose, can you see?

README.md
I've added the correct language to the code areas in the readme, just makes things a little easier to read :)
=> Enable syntax highlighting on code areas in README

lib/algorithms/rsassa.js
=> update: support RSA-PSS in WebCrypto

gulpfile.js, package.json
=> chore(package): update webpack to version 4.8.3

lib/jwe/encrypt.js, test/jwe/alg-mismatch-test.js
=> Bug: better error when given key does not support requested algorithms

gulpfile.js, package-lock.json, package.json, test/algorithms/ecdh-test.js, test/jwe/alg-mismatch-test.js, test/jws/jws-test.js
remove: IE, Safari < latest
add: Safari latest
=> build: update supported test platforms

lib/algorithms/ecdsa.js, lib/algorithms/rsaes.js
This vars was breaking the build on projects
=> Fix problems to build with UglifyJS

gulpfile.js, package.json
Major update to gulp to address the major build issue, and minor bump to a number of other libraries.
=> Update dependencies to build again

AUTHORS, package.json
Signed-off-by: Stephen Augustus <foo@auggie.dev>
=> v2.1.0: Release commit

.github/workflows/presubmits.yml
Signed-off-by: Stephen Augustus <foo@auggie.dev>
=> .github: Extend presubmits to `master` branch

.github/workflows/presubmits.yml
Signed-off-by: Stephen Augustus <foo@auggie.dev>
=> .github: Fix presubmit job name

.github/workflows/codeql.yml
ref: https://codeql.github.com/docs/
Signed-off-by: Stephen Augustus <foo@auggie.dev>
=> .github: Add CodeQL workflow

README.md
correct the description of an arbitrary algorithm usage
resolves #399
=> correct readme #399
